### PR TITLE
Fix fee waiver bug

### PR DESCRIPTION
**Pull request by ryscher**
Fixes the issue with fee waivers not working (https://github.com/CDL-Dryad/dryad-product-roadmap/issues/291). The primary issue was a difference between `country[:name]` (previously used in the code and tests) and `country['country_name']` (the actual structure returned by ROR).

Fixes the secondary display issue on the review page by surfacing the `affiliation.country_name`. (And this also simplifies the logic for `fee_waivered?`)

### CODE REVIEW

**Comment by ryscher** [comment]
I added a test for the new `country_name` method. The feature test will be in a separate PR to the `dryad` repository.

I hadn't deployed this on dev before; it's there now. We should discuss the process for testing PRs...

To test:
1. Create a submission 
2. Set the first author's institution to a university in a low income country, such as:
   - Syed Jamaluddin Afghan University
   - Islamic University of Gaza
   - National University of East Timor
3. Navigate to the "Review and Submit" page
4. Verify that payment is not required, and that the name of the university & country display properly.

**Comment by sfisher** [comment]
Thanks, Ryan.  I'll look at this again with the tests in dryad repo when they're ready.

**Comment by ryscher** [comment]
Feature tests are now in https://github.com/CDL-Dryad/dryad/pull/92

**Comment by sfisher** [comment]
I thought I merged this.

**Pull request merged**
