### PR TITLE
Adding an action to allow submission of URLs

### PR DESCRIPTION
**Pull request by sfisher**
https://github.com/CDL-Dryad/dryad-product-roadmap/issues/78

I've added some testing instructions in a comment there.

### CODE REVIEW

**Comment by sfisher** [comment]
Hi @daisieh,  How were you able to get skipValidation to fail?

I put this in as my json and it seemed to correctly skip validation.  Maybe I just need to document it better.  I know we need documentation changes for all this stuff.

```
{
    "url": "https://raw.githubusercontent.com/CDL-Dryad/stash/f4a586a5e219f0d7c35d9ca8d5819fa6dce73a3a/stash_api/Gemfile.lock",
    "size": 666,
    "mimeType": "cat/meow",
    "skipValidation": true
}
```

From my Postman it sets the mimeType and size I tell it to.

screen shot 2018-10-04 at 4 54 58 pm

**Comment by sfisher** [comment]
> if you submit something without appending "json" on it, you will get a 406 error, but the file upload will still go through. That seems weird.

I believe this has been fixed now.  It was catching HTML with respond-to blocks in the code and telling people to use json, but it should block the whole action rather than just the response in a specific format because that makes the most sense.

Appending .json is a Rails special sauce for telling it you want to render json.  But I think it's more HTTP standard to set the content-type (what you're sending) and accept headers (what you'll accept back).

**Comment by daisieh** [comment]
> Hi @daisieh, How were you able to get skipValidation to fail?
> 
> I put this in as my json and it seemed to correctly skip validation. Maybe I just need to document it better. I know we need documentation changes for all this stuff.

I had "true" in quotes, which apparently was not the right thing to do. Never mind! It's all good.

**Comment by daisieh** [comment]
> I believe this has been fixed now. It was catching HTML with respond-to blocks in the code and telling people to use json, but it should block the whole action rather than just the response in a specific format because that makes the most sense.

If I don't use the json appended, now I get "NoMethodError in StashApi::UrlsController#create undefined method `include?' for nil:NilClass". The url I was using was http://daisiedash.datadryad.org/api/datasets/doi%3A10.5072%2FFK2G162K3S/urls

**Comment by daisieh** [comment]
Looks good now. Merging.

**Pull request merged**
