### PR TITLE
This is a merge based on from the cdluc3 repo

### PR DESCRIPTION
**Pull request by sfisher**
This is mostly rubocop updates, but with a few fixes David put in, a few I did and removing seeds.rb file contents because it would populate tables that do not exist anymore.

I'm getting David to review since he's familiar with most of these changes already.  I tested and it worked and all tests pass.

### CODE REVIEW

**Comment by dmolesUC3** [comment]
The RuboCop stuff looks OK obviously. :) When did we get rid of related identifiers?

**Comment by sfisher** [comment]
IDK that I remember details.  You're the one who got rid of them!  ;-) https://github.com/CDLUC3/stash/blob/master/stash_datacite/db/migrate/20160718225757_drop_tables_related_id_types_and_relation_types.rb

**Comment by dmolesUC3** [comment]
[So you think](https://github.com/CDLUC3/stash_datacite/blob/development/db/migrate/20160718225757_drop_tables_related_id_types_and_relation_types.rb).

**Comment by dmolesUC3** [comment]
And actually, looking at that commit, it's not clear to me whether we need those seeds or not. Maybe not, if `20160718211122_modify_related_identifier_type_as_enum.rb` takes care of them.

**Comment by dmolesUC3** [comment]
Anyway, if the tests pass it's probably fine.

**Comment by dmolesUC3** [comment]
P.S. When you're trying to pin down a commit history, always be suspicious of a commit that affects 1300 files.

**Comment by sfisher** [comment]
Yeah, I didn't see how many it affected since it appeared to be the most recent.  But anyway, all the tests pass and I believe the db schema was rearranged at some point that doesn't require seeds to be populated for these items.

I don't believe any of us have run the rake task to populate seeds in years and it works without it.

**Pull request merged**
