### PR TITLE
Even unverified emails will get populated in DB table if Dryad exposes them for a user after they log in

### PR DESCRIPTION
**Pull request by sfisher**
https://github.com/CDL-Dryad/dryad-product-roadmap/issues/30

Adding the email if unverified and we can get it.  I also made some changes to the user model and use of email as a local variable since email is also an activerecord field so may cause problems or confusion.

I tested this with a new orcid sandbox account after setting the email to partner (and unverified) and it worked for me.

### CODE REVIEW

**Comment by sfisher** [comment]
The reason emails weren't getting added if ORCID allowed us to see them was because they were unverified.

This should now add the email to the user record if we get it from ORCID (public, partner), even if it is not a verified email address by ORCID.

**Comment by daisieh** [comment]
Wait. Do we want to automatically add even unverified email addresses from ORCID? Shouldn't we verify them ourselves in some way before just adding them to our database?

**Comment by dmolesUC3** [comment]
At minimum there should be a verified/unverified flag. Verification might not matter for every use case, but when it does, it would be good to be able to tell.

**Comment by sfisher** [comment]
Added issue https://github.com/CDL-Dryad/dryad-product-roadmap/issues/52 and I'm going to go ahead with the merge in the meantime.

**Pull request merged**
