### PR TITLE
Internal data basics

### PR DESCRIPTION
**Pull request by daisieh**
I still need a bit of help setting up unit tests for this, but I think that this is approximately correct for basic CRUD operations of internal data for journal integration. You should be able to view internal data for any particular resource at something like http://daisiedash.datadryad.org/stash/resources/5/internal_data and GET/POST/etc data like `{"id": 5, "resource_id": 5,"data_type":"duplicateItem","value":"test"}` as well.

### CODE REVIEW

**Comment by sfisher** [comment]
Hi Daisie.  I had some questions about this.  Wouldn't you want the internal data to be in the context of either a resource (or dataset) by default?  I assume you want to view, get or set the internal data on a specific dataset or version.

If that's the case, I'd probably expect to see something like one of these.

GET /api/datasets/<doi>/internal_data (latest version of dataset and its internal data)

Or

GET /api/versions/<version_id>/internal_data (internal data for a specific resource, I think the id for a "version" is actually a resource)

So I'd think you'd want a nested route for the internal data here.

It would likely be very similar to the way "files" is routed if you look at that routes file.  (under versions, you could add a "resources :internal_data shallow: true do".  The shallow means to leave off the nested path for any more levels than in needed.

So for something like a GET you need the path that includes the "version" (which I think is really a resource id).  But for something like an update with PUT you'd just need /api/internal_data/<id>.

I think it will make it easier to work with because we almost always want to GET or POST internal data in context of the resource.

If we decide to expose this to anyone but ourselves, we probably also need to add all the HATEOAS links to related parts of the API ( something like https://spring.io/understanding/HATEOAS ).  We are doing this kind of manually so far, but it's nice to have links to itself, to paging and to related objects to follow in the UI.  You'll see what I mean if you GET something like /api/datasets  .

But for now, we can probably ignore exposing to the outside world.

**Comment by daisieh** [comment]
I think that I assumed the resource_id would be the main identifier of which dataset you were working on, and that's how I placed the view for it in stash_engine. I suppose that doi would also work as an identifier, but I didn't use that because my brain is still thinking in old-Dryad ways and we tend to use the item_id, a monotonically increasing database ID, as the unique internal identifier.

But you're right that it probably should be nested under either datasets or versions in the API. I am not completely clear on the distinction between a resource and a version, but that's a problem for later.

**Comment by sfisher** [comment]
This looks, pretty good.  Sorry, the changes to the URLs also change how some of the IDs come in.

I tested the following:

GET /api/versions/2/internal_data -- this returns all the internal data for resource_id number 2.  Excellent.

GET /api/internal_data/1 -- I get "The action 'show' could not be found for StashApi::InternalDataController"  This would be an action to just show the specific internal data by ID.

POST /api/versions/2/internal_data (with some json in there for data_type and value) -- this works but doesn't set the resource_id for the record.  I believe it may come in as resource_id or version_id in the params hash.  You can check by just putting "byebug" on a line in the method and try a POST request and you should be able to type "params" in the debugger to see what params hash looks like.

PUT /api/internal_data/1 (with some json in there for data_type and value) -- I get an error, probably because it couldn't find the id in the URL to update the record.  I think it's coming in as params[:id] .  (It's from /stash/stash_api/app/controllers/stash_api/internal_data_controller.rb:26:in `update' ).

DELETE /api/internal_data/1 -- I get "Couldn't find StashEngine::InternalDatum without an ID"  Probably because it's not deleting with the params[:id].

**Comment by daisieh** [comment]
Please ignore the weird commit log. I tried to clean it up with rebases but made it uglier instead. Anyway, everything should work as Scott describes now, and it makes so much more sense that way :)

**Comment by sfisher** [comment]
Look great.  Sorry the changes turned bigger than they seemed at first.

**Pull request merged**
