### PR TITLE
Update gulp

### PR DESCRIPTION
**Pull request by briri**
Gulp was 2 versions behind. 4.0 was a major rewrite 
- Updated `package.json` to require gulp 4.0.x
- Updated the `gulpfile.js` to work with the new codebase

@sfisher and @ryscher you may need to update your local `gulp-cli` installations. To do that you should run: `npm install -g gulp` (you may need to use `sudo` there)

Then run `gulp -v` from within the stash_engine directory and you should see:
```shell
> gulp -v
[14:53:19] CLI version 2.0.1
[14:53:19] Local version 4.0.0
```

### CODE REVIEW

**Comment by briri** [comment]
try running `npm install`

**Comment by briri** [comment]
ok, so Scott had some issues that you may encounter as well @ryscher. I've checked in the `package-lock.json` file though so it should make sure we're all using the same JS decency versions going forward.

First, you'll need to make sure you have recent versions of each of node, gulp and bower
```shell
cdl-briley-9m:stash_engine briley$ node -v
v11.10.0
cdl-briley-9m:stash_engine briley$ npm -v
6.7.0
cdl-briley-9m:stash_engine briley$ gulp -v
[10:45:00] CLI version 2.0.1
[10:45:00] Local version 4.0.0
cdl-briley-9m:stash_engine briley$ bower -v
1.8.8
```

Then you should delete the following: `rm stash_engine/package-lock.json` and `rm -rf stash_engine/node_modules`

Then pull down this branch and reinstall all of the dependencies:
```shell
> npm install
> gem install sass_lint
> bower install
```

Then run the following to make sure you have the right dependencies installed:
cdl-briley-9m:stash_engine briley$ npm list --depth=0
dash-ui@1.0.0 /Users/briley/Documents/workspace/stash/stash_engine
├── browser-sync@2.26.3
├── browsersync-ssi@0.2.4
├── del@3.0.0
├── gulp@4.0.0
├── gulp-autoprefixer@6.0.0
├── gulp-clean-css@4.0.0
├── gulp-if@2.0.2
├── gulp-imagemin@5.0.3
├── gulp-jshint@2.1.0
├── gulp-lb-include@0.3.1
├── gulp-modernizr@3.1.0
├── gulp-postcss@8.0.0
├── gulp-sass@4.0.2
├── gulp-scss-lint@1.0.0
├── gulp-shell@0.6.5
├── gulp-sourcemaps@2.6.4
├── gulp-uglify@3.0.1
├── gulp-useref@3.1.6
├── gulp-w3cjs@1.3.1
├── jshint@2.10.1
├── node-sass@4.11.0
├── path@0.12.7
├── postcss-assets@5.0.0
└── run-sequence@2.2.1
```

Finally verify that gulp is working properly. Run `gulp hello` (shouldn't return any errors) and then startup the app from the Dryad directory and make sure the css loads properly (if it doesn't the fonts, logos, etc. will look weird)

**Comment by sfisher** [comment]
Ryan,

I had lots of homebrew issues on my mac getting node to install the latest version.  I essentially had to install, try to link things, got permission denied, deleted directories or changed permissions.  Try reinstalling node again, get the next problem.  Reinstall again.  Etc.

Then I needed to run through all the instructions Joel had in the Readme, Google problems, delete/reinstall/fix something, try again.  Run through instructions again when the css was all messed up.

I got it working again.   Seems working for me now.

**Comment by ryscher** [comment]
This looks good. Everything updates/runs fine on my VM.

One question....In https://github.com/CDL-Dryad/stash/blob/master/stash_engine/ui-library/README.md, there is a reference to `scss_lint`, but above it is `sass_lint`. Typo? Or something different?

**Comment by briri** [comment]
> This looks good. Everything updates/runs fine on my VM.
> 
> One question....In https://github.com/CDL-Dryad/stash/blob/master/stash_engine/ui-library/README.md, there is a reference to `scss_lint`, but above it is `sass_lint`. Typo? Or something different?

Ahh, just a typo in here. sorry about that

**Pull request merged**
