### PR TITLE
Making user migration work.

### PR DESCRIPTION
**Pull request by sfisher**
This should explain the feature https://github.com/CDL-Dryad/dryad-product-roadmap/issues/452

I added unit and ui tests.  This affects both the dryad and stash repos.

### CODE REVIEW

**Comment by ryscher** [comment]
When I receive the email to validate my migration (in the Apple Mail client), the HTML tags are visible. Is there a header missing?

**Comment by ryscher** [comment]
Ok, reinstating my earlier comment -- when the email with the token is received in Apple's Mail.app, the HTML tags are visible, instead of being rendered.

Also, I'm not quite clear on the workflow here... I wasn't able to get a migration to happen through the UI. I tried:
- Find a user1 with associated resources. 
- Copy the user1's email to their old_dryad_email
- Create a new user (user2) and login
- When prompted to migrate, enter the email for user1.
- Then I see see the message that the email doesn't match any that have been used.

**Comment by sfisher** [comment]
Hi Ryan,

That's how I thought it worked at first, also.  But it turns out the code already there uses the *old_dryad_email* simply as a place to store the email you want to take over as part of the validation process.

To get it to work, you need to

1. find a user and change their main email (user.email field and **not** the *old_dryad_email* field).  For a normal user it will not need changing since it is already set to one of their email addresses.  You are just doing this to test.
2. get your token and claim the account.  It should claim because the email you are registering (*old_dryad_email*) has been validated and matches the main email for an account.
3. You have now taken over this former account and your current user is now switched to it.  You will also find anything in your account before you merged accounts will get merged in.
4. Profit!

**Comment by sfisher** [comment]
Hey Ryan.  Try the emailer again.  I think it should be fixed.  It looks like the template was named .text.erb intead of html.erb which is probably why it showed it as a text email in some mail clients.

I think this PR also has the fixes for tests for some of the stuff that got removed.

It turns out that one of the errors seems to be because of problems with Nokogiri connecting to w3.org .

**Comment by sfisher** [comment]
This was tested by John Borghi with a migration and it worked.  I also need some of the testing fixes in subsequent code, so merging.

**Pull request merged**
