### PR TITLE
Removing the manually stored file path

### PR DESCRIPTION
**Pull request by sfisher**
The file path was sometimes wrong on servers because it would find the path without the symlinks and then it would expire with a number of releases being deployed.  I hacked some callbacks in before to update this path, but this is a better fix that isn't just a bad hack to keep it from blowing up.

The ticket for this is https://github.com/CDL-Dryad/dryad-product-roadmap/issues/475 and it also includes a migration to remove that temp_file_path field from the database.  I haven't deployed it to dev yet since it will delete that field and might mess up anything else that depends on the dev database.

I also cleaned up the crazy file that was all duplicate tests for the stash_engine_resource in the stash_datacite engine.  IDK how that got in there.  Brian thought maybe David copied it at some point, but IDK.  Maybe just an accident.

There were also a method or two that were no longer used that I removed.  Overall this isn't too complicated, I hope.

I tried a submission to Merritt and it all seemed to work (I think) against my local database, but it's hard to tell the full cycle without using the real development database and the notifier from Merritt.  Though I don't suspect there will be any problem.

### CODE REVIEW

**Comment by ryscher** [comment]
corrected trivial merge conflict...

**Comment by ryscher** [comment]
This had more interactions with https://github.com/CDL-Dryad/stash/pull/297 than just the simple merge conflict. I've deployed it to dev and it works fine with actual user interactions. I think the issues are completely within the testing framework, and I'm working on resolving the obvious issues.

**Comment by sfisher** [comment]
Yay.  Got tests to pass.  kinda painful with these two different related things coming together.

**Comment by ryscher** [comment]
Ok looks good now. Thanks for fixing all the tests!

**Pull request merged**
